# Generated by Django 3.1.7 on 2021-03-25 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.models import User


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ForeignKey(
                default=User.objects.get(pk=1).id,
                on_delete=django.db.models.deletion.CASCADE,
                to='auth.user'),
            preserve_default=False,
        ),
    ]
