version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.prod.db

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    expose:
      - 8000
    depends_on:
      - "db"

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - "web"

volumes:
  pgdata:
